version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./etc/Dockerfile
    container_name: pdfconverterapi_app
    depends_on:
      - postgres
      - converter
    env_file:
      - .env
    restart: always
    networks:
      global_network:
      default:

  converter:
    build:
      context: ./
      dockerfile: ./etc/converter.Dockerfile
    container_name: pdfconverterapi_converter
    restart: always
    networks:
      default:

  postgres:
    image: postgres:latest
    container_name: pdfconverterapi_db
    restart: always
    env_file:
      - .env
    networks:
      default:

networks:
  global_network:
    external: true
